export enum PaymentStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
}

export enum DeliveryStatus {
  PENDING = "PENDING",
  AWAITING_PICKUP = "AWAITING_PICKUP",
  PACKING = "PACKING",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  READY_TO_SHIP = "READY_TO_SHIP",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
}
