export enum OrderStatus {
  BASKET = "BASKET",
  REQUESTED = "REQUESTED",
  REVIEW_PENDING = "REVIEW_PENDING",
  REVIEW_RESOLVED = "REVIEW_RESOLVED",
  PAYMENT_REQUESTED = "PAYMENT_REQUESTED",
  PAID = "PAID",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  ORDERED = "ORDERED",
  PACKING = "PACKING",
  SHIPPED = "SHIPPED",
  DELIVERED_TO_WAREHOUSE = "DELIVERED_TO_WAREHOUSE",
  SHIPPED_TO_CUSTOMER = "SHIPPED_TO_CUSTOMER",
  DELIVERED_TO_CUSTOMER = "DELIVERED_TO_CUSTOMER",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
  DELETED = "DELETED",
}

export const OrderStatusDisplayNames: Record<OrderStatus, string> = {
  [OrderStatus.BASKET]: "In Basket",
  [OrderStatus.REQUESTED]: "Order Requested",
  [OrderStatus.REVIEW_PENDING]: "Pending Review",
  [OrderStatus.REVIEW_RESOLVED]: "Review Resolved",
  [OrderStatus.PAYMENT_REQUESTED]: "Payment Requested",
  [OrderStatus.PAID]: "Paid",
  [OrderStatus.PAYMENT_FAILED]: "Payment Failed",
  [OrderStatus.ORDERED]: "Ordered",
  [OrderStatus.PACKING]: "Packing",
  [OrderStatus.SHIPPED]: "Shipped",
  [OrderStatus.DELIVERED_TO_WAREHOUSE]: "Delivered to Warehouse",
  [OrderStatus.SHIPPED_TO_CUSTOMER]: "Shipped to Customer",
  [OrderStatus.DELIVERED_TO_CUSTOMER]: "Delivered to Customer",
  [OrderStatus.CANCELLED]: "Cancelled",
  [OrderStatus.RETURN_REQUESTED]: "Return Requested",
  [OrderStatus.RETURNED]: "Returned",
  [OrderStatus.DELETED]: "Deleted",
};
